version: "3.7"
services:
  app:
    build:
      context: ./app
    ports:
      - 5000:5000
    volumes: ['./app:/app']
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./app/db/:/root/app/db/
